mutation createAppointment(
    $kitchen: ID!
    $user: ID!
    $date: String!
    $meal: String!
    $details: String!
) {
    createAppointment(
        kitchen: $kitchen
        user: $user
        date: $date
        meal: $meal
        details: $details
    ) {
        _id
        user
        kitchen
        date
        meal
        details
    }
}
