mutation createAppointments(
    $kitchen: ID!
    $user: ID!
    $dates: [String!]!
    $meals: [String!]!
    $details: [String]
) {
    createAppointments(
        kitchen: $kitchen
        user: $user
        dates: $dates
        meals: $meals
        details: $details
    ) {
        _id
        user
        kitchen
        date
        meal
        details
    }
}
