mutation createMeal(
    $owner: ID!
    $date: String!
    $time: String!
    $mainCourse: String!
) {
    createMeal(
        owner: $owner
        date: $date
        time: $time
        mainCourse: $mainCourse
    ) {
        meal
    }
}
