query GetKitchens {
    getKitchens {
        _id
        name
        address
        knives
        walkin
        utensils
        rate
        imageUrl
        burners
        city
        appointments {
            date
            meal
            details
            user
        }
    }
}
